function [staTable, outStruct] = readSTA(fileName, fileDir)
% readSTA Read Abaqus .sta status file into a table and a per-step struct.
%   [staTable, outStruct] = readSTA(fileName, fileDir)
%
% Inputs:
%   fileName  - char or string: name of the .sta file (extension optional)
%   fileDir   - char or string: directory containing the file
%
% Outputs:
%   staTable  - table containing the parsed .sta records (one row per record)
%   outStruct - struct with fields "step_<n>" where each field is a subtable
%               for the corresponding analysis step
%
% Example:
%   [tbl, byStep] = readSTA('job1','C:\myJobs')
%
% Notes:
%   - Parser expects a standard ABAQUS .sta layout (startRow = 6 in this file).
%   - This function supplements the auto-generated import code and adds
%     post-processing such as removal of trailing NaN rows and an
%     "unconvMask" flag for unconverged attempts.

% Auto-generated by MATLAB on 2025/11/24 16:26:22
% Additional functionality added by Ed Wheatcroft

%% argument validation
arguments
    fileName char
    fileDir char = pwd
end

% process arguments
if ~endsWith(fileName, '.sta','IgnoreCase',true)
    fileName = [fileName, '.sta'];
end

filePath = fullfile(fileDir, fileName);
if ~exist(filePath,"file")
    error(['No STA file found at:', newline, filePath])
end


%% Read columns of data as text:
% hard code start and end rows - this should be a standard ABQUS format
startRow = 6;
endRow = inf;
% For more information, see the TEXTSCAN documentation.
formatSpec = '%4s%6s%5s%5s%6s%6s%12s%11s%12s%11s%s%[^\n\r]';


%% Open the text file.
fileID = fopen(filePath,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{3} = strtrim(dataArray{3});
dataArray{10} = strtrim(dataArray{10});
dataArray{11} = strtrim(dataArray{11});

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,4,5,6,7,8,9]
    % Converts text in the input cell array to numbers. Replaced non-numeric text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;

            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^[-/+]*\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,2,4,5,6,7,8,9]);
rawStringColumns = string(raw(:, [3,10,11]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
staTable = table;
staTable.step = cell2mat(rawNumericColumns(:, 1));
staTable.increment = cell2mat(rawNumericColumns(:, 2));
staTable.attempt = rawStringColumns(:, 1);
staTable.svrDscn = cell2mat(rawNumericColumns(:, 3));
staTable.equilIters = cell2mat(rawNumericColumns(:, 4));
staTable.itersTotal = cell2mat(rawNumericColumns(:, 5));
staTable.timeOrFreqTotal = cell2mat(rawNumericColumns(:, 6));
staTable.timeOrLPFforStep = cell2mat(rawNumericColumns(:, 7));
staTable.timeOrLPFinc = cell2mat(rawNumericColumns(:, 8));
staTable.DOFmonitor = rawStringColumns(:, 2);
staTable.riksFlag = rawStringColumns(:, 3);


%% Added by Ed
%  - Removes the last two rows of the table if they're NaN
%  - Splits the table into its steps. These sub-tables are output as the fields of outStruct
%  - Adds a specific logical variable for un-converged attempts
%  - May add other functionality later to de-textify the attempts and riks flag...

% remove last two rows if they're nan. Take this odd iterative approach in case we read the file before both rows have been written by ABAQUS
for i = 1:2
    if isnan(staTable{end,1})
        staTable(end,:) = [];
    end
end

% add a flag for unconverged attempts
unconvMask = contains(staTable.attempt,'U');
staTable = addvars(staTable, unconvMask, 'After', 'attempt');

% sort into a struct where each field is the .sta table for a single analysis step.
steps = unique(staTable.step);
numSteps = length(steps);
for i = 1:numSteps
    currStepMask = staTable.step == steps(i);
    currStepTab = staTable(currStepMask,:);
    currStepName = ['step_', num2str(steps(i))];
    outStruct.(currStepName) = currStepTab;
end


end




